[[connectors]]
allow_override = ["endpoint", "database", "table", "username", "batch"]
id = "mysql_src"
type = "mysql"

[connectors.params]
batch = 1024
database = "wp_data"
endpoint = "mysql://localhost:3306"
table = "wp_events"
username = "root"
